'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { timetableApi, type TimetableFilters, type TimetableResult, type TimetableSnapshotMetadata, type TimetableSnapshotsQuery } from '@/api/timetable-api';
import TimetableGrid from './TimetableGrid';
import { CustomPagination } from '@/components/ui/pagination';

const filterFields: Array<[keyof TimetableFilters, string]> = [['year', 'Niên học'], ['semester', 'Học kỳ'], ['week', 'Tuần'], ['faculty', 'Khoa'], ['course', 'Khóa'], ['className', 'Lớp']];
const emptyQuery: TimetableSnapshotsQuery = { page: 1, limit: 10 };
const selectionOf = (row: TimetableSnapshotMetadata): TimetableFilters => ({ year: row.year, semester: row.semester, week: row.week, faculty: row.faculty || '', course: row.course || '', className: row.className || '' });

export default function TimetableSnapshotsPanel() {
  const [filters, setFilters] = useState<TimetableSnapshotsQuery>(emptyQuery); const [rows, setRows] = useState<TimetableSnapshotMetadata[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [detail, setDetail] = useState<TimetableResult | null>(null); const [selected, setSelected] = useState<TimetableSnapshotMetadata | null>(null); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState(''); const mounted = useRef(true);
  useEffect(() => () => { mounted.current = false; }, []);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await timetableApi.getSnapshots(filters); if (!mounted.current) return; setRows(result.data); setTotal(result.total); } catch (e: unknown) { if (mounted.current) setError(e instanceof Error ? e.message : 'Không thể tải dữ liệu đã đồng bộ.'); } finally { if (mounted.current) setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  const openDetail = async (row: TimetableSnapshotMetadata) => { setSelected(row); setDetail(null); setError(''); try { setDetail(await timetableApi.getTimetable(selectionOf(row))); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Không thể tải chi tiết thời khóa biểu.'); } };
  const syncAgain = async (row: TimetableSnapshotMetadata) => { setSyncing(true); setMessage(''); setError(''); try { await timetableApi.startSync([selectionOf(row)]); setMessage('Đã gửi yêu cầu đồng bộ lại.'); let attempts = 0; while (attempts < 30) { const status = await timetableApi.getSyncStatus(); if (status.job?.status !== 'running') { if (status.job?.status === 'failed') setError(status.job.error || 'Đồng bộ thất bại.'); else setMessage('Đồng bộ đã hoàn tất.'); await load(); return; } attempts += 1; await new Promise((resolve) => window.setTimeout(resolve, 1000)); } setMessage('Job vẫn đang chạy; hãy làm mới để xem trạng thái.'); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Không thể yêu cầu đồng bộ lại.'); } finally { if (mounted.current) setSyncing(false); } };
  const setFilter = (field: keyof TimetableFilters, value: string) => setFilters((current) => ({ ...current, [field]: value, page: 1 }));
  return <section aria-label="Dữ liệu đã đồng bộ" className="min-w-0 space-y-4 rounded-2xl border border-white/75 bg-white/45 p-4 shadow-sm shadow-slate-300/40 backdrop-blur-md">
    <div><h2 className="text-base font-semibold text-[#1E293B]">Dữ liệu đã đồng bộ</h2><p className="text-sm text-[#64748B]">Xem metadata và mở lịch đã lưu; không chỉnh sửa hoặc xóa snapshot trực tiếp.</p></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{filterFields.map(([field, label]) => <label key={field} className="space-y-1 text-sm font-semibold"><span>{label}</span><input aria-label={label} value={String(filters[field] || '')} onChange={(e) => setFilter(field, e.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2" /></label>)}</div>
    {loading && <p role="status">Đang tải dữ liệu đã đồng bộ...</p>}{error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-700">{message}</p>}
    {!loading && !rows.length && !error && <p role="status" className="rounded-xl bg-amber-500/10 p-3 text-sm text-amber-700">Không có dữ liệu phù hợp.</p>}
    {!!rows.length && <><div className="overflow-x-auto rounded-xl border border-white/70 bg-white/50"><table className="w-full min-w-[900px] text-left text-sm"><caption className="p-2 text-left font-semibold">Danh sách snapshot</caption><thead><tr><th className="p-2">Niên học</th><th className="p-2">Học kỳ</th><th className="p-2">Tuần</th><th className="p-2">Khoa / Khóa / Lớp</th><th className="p-2">Đồng bộ lúc</th><th className="p-2">Thao tác</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.coverageKey}-${row.syncedAt}`} className="border-t border-white/70"><td className="p-2">{row.year}</td><td className="p-2">{row.semester}</td><td className="p-2">{row.week}</td><td className="p-2">{[row.faculty, row.course, row.className].filter(Boolean).join(' · ') || 'Tất cả'}</td><td className="p-2">{new Date(row.syncedAt).toLocaleString('vi-VN')}</td><td className="p-2"><button type="button" onClick={() => void openDetail(row)} className="mr-2 rounded-lg border px-2 py-1">Xem chi tiết</button><button type="button" disabled={syncing} onClick={() => void syncAgain(row)} className="rounded-lg bg-[#1A73E8] px-2 py-1 text-white disabled:opacity-50">Đồng bộ lại</button></td></tr>)}</tbody></table></div><CustomPagination totalItems={total} pageSize={filters.limit || 10} currentPage={filters.page || 1} onPageChange={(page) => setFilters((current) => ({ ...current, page }))} onPageSizeChange={(limit) => setFilters((current) => ({ ...current, page: 1, limit }))} /></>}
    {selected && <div className="rounded-xl border border-blue-200 bg-blue-50/60 p-3"><h3 className="font-semibold">Chi tiết: {selected.year} · {selected.semester} · {selected.week}</h3>{detail ? <TimetableGrid result={detail} /> : !error && <p role="status">Đang tải chi tiết...</p>}</div>}
  </section>;
}
