'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useAuth } from '@/providers/auth-provider';
import { classApi, type Class } from '@/api/class-api';
import { timetableApi, type TimetableClassLink, type TimetableClassSelection, type TimetableClassSyncStatus, type TimetableFilters, type TimetableOptions, type TimetableSyncJob, type TimetableSyncSettings } from '@/api/timetable-api';

const emptySettings: TimetableSyncSettings = { enabled: false, intervalMinutes: 60, coverage: [], selectedClasses: [], classLinks: [] };
const normalize = (value: unknown) => String(value || '').normalize('NFKC').replace(/\s+/gu, ' ').trim().toLocaleLowerCase();
const selectionKey = (item: TimetableClassSelection) => JSON.stringify([item.year, item.semester, item.faculty || '', item.course || '', item.className]);
const statusLabel = (status: string) => ({ valid: 'Đã đồng bộ', pending: 'Đang chờ', running: 'Đang chạy', failed: 'Lỗi', configuration: 'Chưa đủ cấu hình', missing: 'Chưa đồng bộ' }[status] || status);

export default function TimetableSyncPanel({ onSynced }: { onSynced?: () => void }) {
  const { user } = useAuth(); const isAdmin = String(user?.roleCode || '').toUpperCase() === 'ADMIN';
  const [classes, setClasses] = useState<Class[]>([]); const [catalog, setCatalog] = useState<TimetableOptions | null>(null);
  const [context, setContext] = useState<Pick<TimetableFilters, 'year' | 'semester' | 'faculty' | 'course'>>({ year: '', semester: '', faculty: '', course: '' });
  const [settings, setSettings] = useState<TimetableSyncSettings>(emptySettings); const [statuses, setStatuses] = useState<TimetableClassSyncStatus[]>([]); const [job, setJob] = useState<TimetableSyncJob | null>(null); const [lastUpdate, setLastUpdate] = useState<string | null>(null);
  const [view, setView] = useState<'system' | 'source'>('system'); const [search, setSearch] = useState(''); const [department, setDepartment] = useState(''); const [linkStatus, setLinkStatus] = useState('all'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const callback = useRef(onSynced);
  useEffect(() => { callback.current = onSynced; }, [onSynced]);
  useEffect(() => { if (!isAdmin) return; let active = true; void Promise.all([classApi.getClasses(), timetableApi.getSyncStatus(), timetableApi.loadCatalog({})]).then(([roster, data, initialCatalog]) => { if (!active) return; const next = data.settings || emptySettings; setClasses(roster); setCatalog(initialCatalog); setSettings({ ...emptySettings, ...next, classLinks: next.classLinks || [] }); setStatuses(data.classStatuses || []); setJob(data.job); setLastUpdate(data.lastSuccessfulUpdate); }).catch((e: Error) => active && setError(e.message)); return () => { active = false; }; }, [isAdmin]);
  useEffect(() => { if (!isAdmin || !job || !['running', 'pending'].includes(job.status)) return; const timer = window.setInterval(() => void timetableApi.getSyncStatus().then((data) => { setJob(data.job); setStatuses(data.classStatuses || []); setLastUpdate(data.lastSuccessfulUpdate); if (data.job && !['running', 'pending'].includes(data.job.status)) callback.current?.(); }).catch(() => undefined), 2000); return () => window.clearInterval(timer); }, [isAdmin, job?.id, job?.status]);
  const loadCatalog = async () => { setBusy(true); setError(''); try { setCatalog(await timetableApi.loadCatalog(context)); } catch (e: unknown) { setCatalog(null); setError(e instanceof Error ? e.message : 'Không thể tải danh mục nguồn.'); } finally { setBusy(false); } };
  const setContextValue = (key: keyof typeof context, value: string) => setContext((current) => ({ ...current, [key]: value }));
  const sourceRows = catalog?.classes || [];
  const draftFor = (item: Class) => settings.classLinks?.find((link) => link.systemClassId === item._id);
  const matchingOptions = (item: Class) => sourceRows.filter((option) => normalize(option.label) === normalize(item.class_name));
  const makeLink = (item: Class, source: { label: string; value: string }, method: 'auto' | 'manual'): TimetableClassLink => ({ systemClassId: item._id, year: context.year, semester: context.semester, faculty: context.faculty || '', course: context.course || '', className: source.value, sourceLabel: source.label, matchMethod: method });
  const setLink = (item: Class, source: { label: string; value: string } | null, method: 'auto' | 'manual' = 'manual') => setSettings((current) => ({ ...current, classLinks: source ? [...(current.classLinks || []).filter((link) => link.systemClassId !== item._id), makeLink(item, source, method)] : (current.classLinks || []).filter((link) => link.systemClassId !== item._id) }));
  const reconcile = () => { if (!catalog) return; setSettings((current) => { const links = [...(current.classLinks || [])]; classes.forEach((item) => { if (!links.some((link) => link.systemClassId === item._id)) { const matches = matchingOptions(item); if (matches.length === 1) links.push(makeLink(item, matches[0], 'auto')); } }); return { ...current, classLinks: links }; }); setMessage('Đã tạo liên kết duy nhất thành bản nháp; hãy kiểm tra và lưu.'); };
  const save = async () => { setBusy(true); setError(''); setMessage(''); try { const next = await timetableApi.updateSyncSettings(settings); setSettings({ ...emptySettings, ...next, classLinks: next.classLinks || [] }); setMessage('Đã lưu liên kết và cấu hình.'); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Không thể lưu cấu hình.'); } finally { setBusy(false); } };
  const statusFor = (link: TimetableClassLink) => statuses.find((row) => selectionKey(row.classSelection) === selectionKey(link));
  const departments = useMemo(() => [...new Set(classes.map((item) => typeof item.dept_id === 'object' ? `${(item.dept_id as any).name || ''}|${(item.dept_id as any).code || ''}` : String(item.dept_id || '')))].filter(Boolean), [classes]);
  const filteredClasses = useMemo(() => classes.filter((item) => { const dept = typeof item.dept_id === 'object' ? `${(item.dept_id as any).name || ''}|${(item.dept_id as any).code || ''}` : String(item.dept_id || ''); const linked = Boolean(draftFor(item)); return (!normalize(search) || normalize(item.class_name).includes(normalize(search))) && (!department || dept === department) && (linkStatus === 'all' || (linkStatus === 'linked' ? linked : !linked)); }), [classes, search, department, linkStatus, settings.classLinks]);
  const unlinkedSourceRows = sourceRows.filter((source) => !(settings.classLinks || []).some((link) => link.className === source.value && link.year === context.year && link.semester === context.semester));
  if (!isAdmin) return null;
  return <section aria-label="Quản trị đồng bộ thời khóa biểu" className="min-w-0 space-y-3 rounded-2xl border border-white/75 bg-white/45 p-4 shadow-sm shadow-slate-300/40 backdrop-blur-md">
    <div><h2 className="text-base font-semibold text-[#1E293B]">Quản trị đồng bộ</h2><p className="text-sm text-[#64748B]">Đối chiếu toàn bộ lớp hệ thống với danh mục lớp nguồn.</p></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{(['year', 'semester', 'faculty', 'course'] as const).map((key) => <label key={key} className="space-y-1 text-sm font-semibold"><span>{key === 'year' ? 'Niên học nguồn' : key === 'semester' ? 'Học kỳ nguồn' : key === 'faculty' ? 'Khoa nguồn' : 'Khóa nguồn'}</span><select aria-label={key} value={context[key] || ''} onChange={(e) => setContextValue(key, e.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-2 py-2"><option value="">{key === 'year' || key === 'semester' ? 'Chọn' : 'Tất cả'}</option>{(catalog?.[key === 'year' ? 'years' : key === 'semester' ? 'semesters' : key === 'faculty' ? 'faculties' : 'courses'] || []).filter((option) => option.value).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}</div>
    <div className="flex flex-wrap gap-2"><button type="button" onClick={() => void loadCatalog()} disabled={busy || !context.year || !context.semester} className="rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50">Tải danh mục nguồn</button><button type="button" onClick={reconcile} disabled={busy || !catalog} className="rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50">Đối chiếu lớp</button><label className="flex items-center gap-2 text-sm"><span>Khoảng đồng bộ</span><input aria-label="Khoảng đồng bộ" type="number" min={30} value={settings.intervalMinutes} onChange={(e) => setSettings((current) => ({ ...current, intervalMinutes: Number(e.target.value) }))} className="w-20 rounded-lg border px-2 py-2" /></label><button type="button" onClick={() => void save()} disabled={busy} className="rounded-xl bg-[#1A73E8] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Lưu liên kết</button></div>
    {job && <p role="status" className="rounded-xl bg-blue-500/10 px-3 py-2 text-sm">{job.status === 'succeeded' ? 'Đồng bộ hoàn tất' : job.status === 'failed' ? 'Đồng bộ có lỗi' : 'Đang đồng bộ'} · {job.completed || 0}/{job.total || 0}</p>}{lastUpdate && <p className="text-xs text-slate-600">Cập nhật gần nhất: {new Date(lastUpdate).toLocaleString('vi-VN')}</p>}
    <div className="flex flex-wrap items-center gap-3"><input aria-label="Tìm lớp" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm lớp hệ thống" className="rounded-lg border px-3 py-2 text-sm" /><select aria-label="Khoa hệ thống" value={department} onChange={(e) => setDepartment(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">Tất cả khoa</option>{departments.map((value) => <option key={value} value={value}>{value.replace('|', ' · ')}</option>)}</select><select aria-label="Trạng thái liên kết" value={linkStatus} onChange={(e) => setLinkStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="all">Mọi trạng thái</option><option value="linked">Đã liên kết</option><option value="unlinked">Chưa liên kết</option></select><select aria-label="Kiểu hiển thị" value={view} onChange={(e) => setView(e.target.value as 'system' | 'source')} className="rounded-lg border px-3 py-2 text-sm"><option value="system">Lớp hệ thống</option><option value="source">Lớp nguồn / chưa liên kết</option></select><span className="text-sm text-slate-600">{classes.length} lớp hệ thống</span></div>
    <div className="overflow-x-auto rounded-xl border border-white/70 bg-white/50"><table className="min-w-[980px] w-full text-left text-sm"><caption className="p-2 text-left font-semibold">Bảng quản lý liên kết lớp</caption><thead><tr className="border-t border-white/70"><th className="p-2">Lớp hệ thống</th><th className="p-2">Lớp nguồn</th><th className="p-2">Phương thức</th><th className="p-2">Trạng thái tuần</th><th className="p-2">Thao tác</th></tr></thead><tbody>{view === 'system' ? filteredClasses.map((item) => { const link = draftFor(item); const matches = matchingOptions(item); const status = link && statusFor(link); return <tr key={item._id} className="border-t border-white/70 align-top"><td className="p-2 font-semibold">{item.class_name}<div className="text-xs font-normal text-slate-600">{item.class_year}</div></td><td className="p-2"><select aria-label={`Nguồn cho ${item.class_name}`} value={link?.className || ''} onChange={(e) => { const option = sourceRows.find((candidate) => candidate.value === e.target.value); setLink(item, option || null); }} className="w-full rounded-lg border border-slate-300 bg-white px-2 py-1"><option value="">Chưa liên kết / unverified</option>{(matches.length ? matches : sourceRows).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{link && <div className="text-xs text-slate-600">{link.sourceLabel} · {link.year}/{link.semester}</div>}</td><td className="p-2">{link ? (link.matchMethod === 'auto' ? 'Tự động (unique)' : 'Thủ công') : matches.length > 1 ? 'Cần chọn thủ công' : 'Unverified'}</td><td className="p-2">{status ? statusLabel(status.status) : 'Chưa sẵn sàng'}</td><td className="p-2"><button type="button" disabled={!link || !status?.weeks?.length || busy} onClick={() => { const week = status?.weeks?.[0]?.week; if (link && week) void timetableApi.syncSavedClassWeek({ ...link, week }, 'sync').then(() => callback.current?.()); }} className="rounded-lg bg-[#1A73E8] px-2 py-1 text-white disabled:opacity-50">Đồng bộ tuần</button><button type="button" disabled={!link || busy} onClick={() => setLink(item, null)} className="ml-2 rounded-lg border px-2 py-1 disabled:opacity-50">Bỏ liên kết</button></td></tr>; }) : unlinkedSourceRows.map((source) => <tr key={source.value} className="border-t border-white/70"><td className="p-2">—<div className="text-xs text-slate-600">Không có lớp hệ thống tương ứng</div></td><td className="p-2 font-semibold">{source.label}</td><td className="p-2">Source-only</td><td className="p-2">Chưa liên kết</td><td className="p-2">Không đủ điều kiện đồng bộ</td></tr>)}</tbody></table></div>
    {message && <p role="status" className="text-sm text-emerald-700">{message}</p>}{error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-700">{error}</p>}
  </section>;
}
