import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import TimetableGrid from './TimetableGrid';
it.each([['Sáng', 1], ['Chiều', 7], ['Tối', 13]] as const)('renders six periods for %s and bounds merged cells', (sessionLabel, start) => {
  const { container } = render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, periods: Array.from({ length: 18 }, (_, index) => String(index + 1)), lessons: [{ sessionLabel, day: 1, startPeriod: start, endPeriod: start + 7, subject: 'Môn học' }], isEmpty: false }} />);
  expect(Array.from(container.querySelectorAll('tbody tr')).map((row) => Array.from(row.querySelectorAll('th')).find((cell) => cell.textContent?.startsWith('Tiết '))?.textContent)).toEqual(Array.from({ length: 6 }, (_, index) => `Tiết ${start + index}`));
  expect(screen.getByText('Môn học').closest('td')).toHaveAttribute('rowspan', '6');
  expect(screen.getByText(sessionLabel)).toHaveAttribute('rowspan', '6');
});
describe('TimetableGrid', () => {
  it('renders source dates on all seven day headers', () => { render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, startDate: '2026-09-14', endDate: '2026-09-20', periods: ['1'], lessons: [], isEmpty: true }} />); expect(screen.getByText('Thứ 2 · 14/09')).toBeInTheDocument(); expect(screen.getByText('Chủ nhật · 20/09')).toBeInTheDocument(); });
  it('keeps merged multi-period lesson and all week columns', () => { render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, periods: ['13', '14'], lessons: [{ day: 1, startPeriod: 13, endPeriod: 14, subject: 'Toán', teacher: 'Cô A' }], isEmpty: false }} />); expect(screen.getByText('Toán')).toBeInTheDocument(); expect(screen.getByText('Chủ nhật')).toBeInTheDocument(); });
  it('renders optional lesson details and does not duplicate duration in source time', () => { render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, periods: ['1', '2'], lessons: [{ day: 1, startPeriod: 1, endPeriod: 2, subject: 'CD-TTCAD-CAM', teacher: 'ThS. Nguyễn Nhơn Hải', room: 'B0.7 (TH-QTMMT)', durationLabel: '(5h)', sourceTime: '06:00-09:15 (5h)', onlineUrl: 'https://meet.google.com/test' }], isEmpty: false }} />); expect(screen.getByText('GV: ThS. Nguyễn Nhơn Hải')).toBeInTheDocument(); expect(screen.getByText('Phòng: B0.7 (TH-QTMMT)')).toBeInTheDocument(); expect(screen.getByText('Thời lượng: (5h)')).toBeInTheDocument(); expect(screen.getByText('06:00-09:15')).toBeInTheDocument(); expect(screen.queryByText('06:00-09:15 (5h)')).not.toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Họp trực tuyến' })).toHaveAttribute('href', 'https://meet.google.com/test'); });
  it('keeps missing details and unsafe URLs absent from the grid', () => { render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, periods: ['1'], lessons: [{ day: 1, startPeriod: 1, endPeriod: 1, subject: 'Môn học' }], isEmpty: false }} />); expect(screen.getByText('Môn học')).toBeInTheDocument(); expect(screen.queryByText(/GV:/)).not.toBeInTheDocument(); expect(screen.queryByText(/Phòng:/)).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Họp trực tuyến' })).not.toBeInTheDocument(); });
  it('exposes a keyboard-focusable named scroll region and visible hint', () => { render(<TimetableGrid result={{ filters: { year: 'y', semester: 's', week: 'w' }, periods: ['1'], lessons: [], isEmpty: false }} />); const region = screen.getByRole('region', { name: /vùng cuộn ngang/i }); expect(region).toHaveAttribute('tabindex', '0'); expect(region).toHaveAttribute('aria-describedby', 'timetable-grid-hint'); expect(screen.getByText(/Vuốt ngang/)).toBeInTheDocument(); expect(screen.getByText('Tiết 1')).toHaveClass('sticky'); });
});
