'use client';
import type { TimetableResult } from '@/api/timetable-api';

const days = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ nhật'];

export default function TimetableGrid({ result }: { result: TimetableResult }) {
  const sourcePeriods = result.periods.length ? result.periods.map(Number) : Array.from({ length: 18 }, (_, index) => index + 1);
  const groups = Array.from(new Set(result.lessons.map((lesson) => `${lesson.classLabel || result.classLabel || 'Tất cả lớp'}\u0000${lesson.sessionLabel || result.sessionLabel || ''}`)));
  if (!groups.length) groups.push(`${result.classLabel || 'Tất cả lớp'}\u0000${result.sessionLabel || ''}`);
  const lessonsByGroup = (key: string) => result.lessons.filter((lesson) => `${lesson.classLabel || result.classLabel || 'Tất cả lớp'}\u0000${lesson.sessionLabel || result.sessionLabel || ''}` === key);
  return <div className="min-w-0 space-y-2"><p id="timetable-grid-hint" className="text-xs text-[#64748B]">Vuốt ngang hoặc dùng Shift + con trỏ để xem đủ các ngày.</p><div role="region" aria-label="Bảng thời khóa biểu, vùng cuộn ngang" aria-describedby="timetable-grid-hint" tabIndex={0} className="min-w-0 overflow-x-auto rounded-2xl border border-white/75 bg-white/45 shadow-sm shadow-slate-300/40 backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-[#1A73E8]/30" data-testid="timetable-grid">
    <table className="min-w-[1120px] w-full border-collapse text-xs"><thead><tr className="bg-white/80"><th className="min-w-28 border border-white/70 p-2 text-left">Lớp học</th><th className="min-w-20 border border-white/70 p-2 text-left">Buổi</th><th className="sticky left-0 z-20 min-w-20 border border-white/70 bg-white p-2 text-left">Tiết</th>{days.map((day) => <th key={day} className="min-w-32 border border-white/70 p-2 text-center">{day}</th>)}</tr></thead>
      <tbody>{groups.flatMap((groupKey) => { const [classLabel, sessionLabel] = groupKey.split('\u0000'); const lessons = lessonsByGroup(groupKey); const session = sessionLabel.trim().toLocaleLowerCase('vi'); const start = session === 'sáng' ? 1 : session === 'chiều' ? 7 : session === 'tối' ? 13 : null; const periods = start === null ? sourcePeriods : Array.from({ length: 6 }, (_, index) => start + index); const occupied = new Set<string>(); return periods.map((period, periodIndex) => { const cells: React.ReactNode[] = []; if (periodIndex === 0) { cells.push(<th key="class" rowSpan={periods.length} className="border border-white/70 bg-white/90 p-2 text-left align-top font-bold">{classLabel}</th>); cells.push(<th key="session" rowSpan={periods.length} className="border border-white/70 bg-white/90 p-2 text-left align-top">{sessionLabel || '—'}</th>); } cells.push(<th key="period" className="sticky left-0 z-10 border border-white/70 bg-white/90 p-2 text-left font-bold">Tiết {period}</th>); days.forEach((_, dayIndex) => { const occupancyKey = `${dayIndex + 1}:${period}`; if (occupied.has(occupancyKey)) return; const lesson = lessons.find((item) => item.day === dayIndex + 1 && item.startPeriod <= period && item.endPeriod >= period); if (!lesson) { cells.push(<td key={dayIndex} className="border border-white/70 bg-white/35 p-2 align-top" />); return; } const span = Math.max(1, periods.slice(periodIndex).filter((value) => value <= lesson.endPeriod).length); for (let next = period; next < period + span; next += 1) occupied.add(`${dayIndex + 1}:${next}`); cells.push(<td key={dayIndex} rowSpan={span} className="border border-white/70 bg-blue-500/10 p-2 align-top text-[#1E293B]"><div className="space-y-1 break-words"><div className="font-bold text-[#1A73E8]">{lesson.subject}</div>{lesson.subjectCode && <div>Mã: {lesson.subjectCode}</div>}{lesson.teacher && <div>GV: {lesson.teacher}</div>}{lesson.room && <div>Phòng: {lesson.room}</div>}{lesson.sourceTime && <div className="text-[#64748B]">{lesson.sourceTime}</div>}</div></td>); }); return <tr key={`${groupKey}-${period}`}>{cells}</tr>; }); })}</tbody></table>
  </div></div>;
}
