'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { timetableApi, type TimetableFilters, type TimetableOption, type TimetableOptions, type TimetableResult } from '@/api/timetable-api';
import TimetableGrid from './TimetableGrid';

const emptyOptions: TimetableOptions = { years: [], semesters: [], weeks: [], faculties: [], courses: [], classes: [] };
const fields: Array<[keyof TimetableFilters, string]> = [['year', 'Niên học'], ['semester', 'Học kỳ'], ['week', 'Tuần'], ['faculty', 'Khoa'], ['course', 'Khóa'], ['className', 'Lớp']];
export default function TimetableLookup() {
  const [options, setOptions] = useState(emptyOptions); const [filters, setFilters] = useState<TimetableFilters>({ year: '', semester: '', week: '' }); const [result, setResult] = useState<TimetableResult | null>(null); const [state, setState] = useState<'loading' | 'ready' | 'empty' | 'error'>('loading'); const [error, setError] = useState(''); const requestId = useRef(0);
  const loadOptions = async (next: Partial<TimetableFilters> = {}) => { const id = ++requestId.current; setState('loading'); try { const data = await timetableApi.getOptions(next); if (id === requestId.current) { setOptions(data); setState('ready'); } } catch (e: any) { if (id === requestId.current) { setError(e?.message || 'Không thể tải bộ lọc.'); setState('error'); } } };
  useEffect(() => { void loadOptions(); }, []);
  const setFilter = (key: keyof TimetableFilters, value: string) => { const next = { ...filters, [key]: value }; if (key === 'year') { next.semester = ''; next.week = ''; next.faculty = ''; next.course = ''; next.className = ''; } if (key === 'semester') { next.week = ''; next.faculty = ''; next.course = ''; next.className = ''; } if (key === 'faculty') { next.course = ''; next.className = ''; } if (key === 'course') next.className = ''; setFilters(next); setResult(null); void loadOptions(next); };
  const search = async () => { const id = ++requestId.current; setState('loading'); setError(''); try { const data = await timetableApi.getTimetable(filters); if (id === requestId.current) { setResult(data); setState(data.isEmpty ? 'empty' : 'ready'); } } catch (e: any) { if (id === requestId.current) { setError(e?.message || 'Không thể tải thời khóa biểu.'); setState('error'); } } };
  const optionMap = useMemo<Record<string, TimetableOption[]>>(() => ({ year: options.years, semester: options.semesters, week: options.weeks, faculty: options.faculties, course: options.courses, className: options.classes }), [options]);
  return <section className="space-y-5" aria-label="Tra cứu thời khóa biểu"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key, label]) => <label key={key} className="space-y-1 text-sm font-semibold"><span>{label}</span><select aria-label={label} value={filters[key] || ''} onChange={(event) => setFilter(key, event.target.value)} disabled={state === 'loading' && !options.years.length} className="h-10 w-full rounded-xl border border-white/80 bg-white/75 px-3 text-sm"><option value="">Chọn {label.toLowerCase()}</option>{optionMap[key].map((item) => <option key={`${item.value}-${item.label}`} value={item.value}>{item.label}</option>)}</select></label>)}</div><button type="button" onClick={() => void search()} disabled={!filters.year || !filters.semester || !filters.week || state === 'loading'} className="rounded-xl bg-blue-600 px-5 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Tìm kiếm</button>{state === 'loading' && <p role="status">Đang tải thời khóa biểu...</p>}{state === 'error' && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{state === 'empty' && <p role="status" className="rounded-xl bg-amber-50 p-4 text-amber-800">Không có lịch cho bộ lọc đã chọn.</p>}{result && state === 'ready' && <><p className="text-sm text-slate-600">Kết quả: {result.filters.year} · Học kỳ {result.filters.semester} · Tuần {result.filters.week}</p><TimetableGrid result={result} /></>}</section>;
}
