'use client';

import { RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { dormitoryApi, DormDashboardStats } from '@/api/dormitory-api';

const groups: Array<[keyof DormDashboardStats, string]> = [['rooms', 'Phòng'], ['beds', 'Giường'], ['students', 'Sinh viên'], ['dormitory_fees', 'Phí ký túc xá'], ['utilities', 'Điện / nước']];

export default function DormitoryDashboardPage() {
  const [data, setData] = useState<DormDashboardStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const request = useRef(0);
  const load = useCallback(async (initial = false) => { const id = ++request.current; if (initial) setLoading(true); setError(''); try { const next = await dormitoryApi.reports.getDashboardStats(); if (id === request.current) setData(next); } catch (err: any) { if (id === request.current) setError(err?.message || 'Không thể tải dữ liệu tổng quan.'); } finally { if (id === request.current) setLoading(false); } }, []);
  useEffect(() => { void load(true); }, [load]);
  if (loading && !data) return <main className="mx-auto w-full max-w-7xl space-y-6 p-4 md:p-6"><div className="h-8 w-64 animate-pulse rounded bg-white/60" /><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-36 animate-pulse rounded-2xl bg-white/60" />)}</div></main>;
  if (error && !data) return <main className="mx-auto max-w-3xl p-8 text-center"><h1 className="text-xl font-bold text-slate-800">Không thể tải tổng quan</h1><p className="mt-2 text-sm text-slate-500">{error}</p><button className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => void load(true)}>Thử lại</button></main>;
  return <main className="mx-auto w-full max-w-7xl space-y-6 p-4 md:p-6"><header className="flex items-center justify-between"><div><p className="text-sm font-medium text-blue-600">Ký túc xá</p><h1 className="text-2xl font-bold text-slate-900">Tổng quan</h1></div><button aria-label="Làm mới dữ liệu" title="Làm mới" className="rounded-xl border border-white/80 bg-white/60 p-2 text-slate-600 hover:bg-white disabled:opacity-50" disabled={loading} onClick={() => void load()}><RefreshCw size={18} className={loading ? 'animate-spin' : ''} /></button></header>{error && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Dữ liệu hiện tại chưa được làm mới: {error}</p>}<section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">{groups.map(([key, label]) => { const value: any = data?.[key]; return <article key={String(key)} className="rounded-2xl border border-white/70 bg-white/55 p-5 shadow-sm backdrop-blur-md"><h2 className="text-sm font-semibold text-slate-500">{label}</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(value || {}).map(([name, count]) => <div key={name}><p className="text-2xl font-bold text-slate-900">{count as number}</p><p className="text-xs text-slate-500">{name.replaceAll('_', ' ')}</p></div>)}</div></article>; })}</section><section className="rounded-2xl border border-white/70 bg-white/55 p-5 shadow-sm backdrop-blur-md"><h2 className="text-lg font-bold text-slate-800">So sánh 6 tháng</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{(data?.monthly || []).map(month => <div key={month.month} className="rounded-xl bg-white/60 p-3"><p className="text-xs font-semibold text-slate-500">{month.month}</p><p className="mt-2 text-sm text-blue-700">Đăng ký: {month.registrations}</p><p className="text-sm text-emerald-700">Nhận vào: {month.move_ins}</p><p className="text-sm text-amber-700">Phí: {month.dormitory_fee_paid}/{month.dormitory_fee_unpaid}</p><p className="text-sm text-cyan-700">Điện nước: {month.utility_paid}/{month.utility_unpaid}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Chú thích: các cặp số phí và điện nước lần lượt là đã thanh toán / chưa thanh toán.</p></section></main>;
}
