import { createHash } from 'crypto';
import { PdfTemplateFormatter, PdfTemplateLayout, PdfTemplateStyle, PdfTemplateTypeDescriptor } from '../pdf-template/types';

export const DORMITORY_ROSTER_APPLICATION = 'DORMITORY_ROSTER_APPLICATION' as const;
const style: PdfTemplateStyle = { fontFamily: 'Times-Roman', fontSize: 11, minFontSize: 7, fontWeight: 400, color: '#000000', horizontalAlign: 'left', verticalAlign: 'middle', lineHeight: 1.15, padding: 0.5, background: 'transparent', overflow: 'shrink', maxLines: 1 };
const fields = [
  ['student.fullName', 'Họ và tên', 'string'], ['student.dateOfBirth', 'Ngày sinh', 'date'], ['student.gender', 'Giới tính', 'string'], ['student.className', 'Lớp', 'string'], ['student.faculty', 'Khoa', 'string'], ['applicant.ethnicity', 'Dân tộc', 'string'], ['applicant.religion', 'Tôn giáo', 'string'], ['roster.phone', 'Điện thoại', 'string'], ['applicant.citizenId', 'Số căn cước', 'string'], ['applicant.citizenIssueDate', 'Ngày cấp căn cước', 'date'], ['applicant.citizenIssuePlace', 'Nơi cấp căn cước', 'string'], ['applicant.permanentAddress', 'Địa chỉ thường trú', 'string'], ['parent.father.name', 'Họ tên cha', 'string'], ['parent.father.age', 'Tuổi cha', 'number'], ['parent.father.address', 'Địa chỉ cha', 'string'], ['parent.father.contactAddress', 'Nơi ở hiện tại của cha', 'string'], ['parent.father.occupation', 'Nghề nghiệp cha', 'string'], ['parent.father.phone', 'Điện thoại cha', 'string'], ['parent.mother.name', 'Họ tên mẹ', 'string'], ['parent.mother.age', 'Tuổi mẹ', 'number'], ['parent.mother.address', 'Địa chỉ mẹ', 'string'], ['parent.mother.contactAddress', 'Nơi ở hiện tại của mẹ', 'string'], ['parent.mother.occupation', 'Nghề nghiệp mẹ', 'string'], ['parent.mother.phone', 'Điện thoại mẹ', 'string'], ['applicant.priority', 'Diện chính sách', 'string'],
] as const;
const bounds = [[296, 191, 240, 18], [323.5, 215, 77, 18], [459, 215, 77, 18], [218, 239, 142, 18], [396.8, 239, 139, 18], [241, 263, 56, 18], [354.5, 263, 49, 18], [466.4, 263, 69.6, 18], [235.2, 287, 70, 18], [362.5, 287, 63, 18], [480.7, 287, 55, 18], [203, 311, 332, 18], [152.4, 335, 239.6, 18], [396.8, 335, 139.2, 18], [203, 359, 332, 18], [194.9, 383, 341.1, 18], [194.9, 407, 114.9, 18], [375.9, 407, 160.1, 18], [152.4, 431, 196, 18], [386.4, 431, 149.6, 18], [203, 455, 332, 18], [194.9, 479, 341.1, 18], [194.9, 503, 114.9, 18], [375.9, 503, 160.1, 18], [302.8, 527, 233.3, 18]] as const;
const key = (index: number) => fields[index][0];
export const DORMITORY_ROSTER_APPLICATION_DESCRIPTOR: PdfTemplateTypeDescriptor = {
  moduleCode: 'DORMITORY', featureCode: 'DORMITORY_ROSTER', templateTypeCode: DORMITORY_ROSTER_APPLICATION, displayName: 'Mẫu đơn đăng ký KTX', sourcePermission: 'DORM_REG_READ',
  fields: fields.map(([fieldKey, label, dataType]) => ({ key: fieldKey, label, dataType: dataType as any, sensitive: fieldKey.includes('fullName') || fieldKey.includes('citizen') || fieldKey.includes('phone'), syntheticSample: fieldKey.toLowerCase().includes('date') ? '02/01/2004' : 'Giá trị mẫu', allowedFormatters: (fieldKey.toLowerCase().includes('date') ? ['date_ddmmyyyy'] : ['plain', ...(fieldKey.endsWith('gender') ? ['gender_vi'] : [])]) as PdfTemplateFormatter[], defaultStyle: { ...style, overflow: 'shrink', maxLines: 1 } })),
  pagePolicy: { minPages: 1, maxPages: 10, allowedDimensions: { width: 595.32, height: 842.04, tolerance: 2 } },
  syntheticFixture: (name) => ({ name, values: Object.fromEntries(fields.map(([fieldKey], index) => [fieldKey, name === 'missing' && index % 3 === 0 ? '' : name === 'long' ? `${fieldKey} - Giá trị rất dài để kiểm tra wrap và shrink trong biểu mẫu ký túc xá` : name === 'vietnamese' ? 'Nguyễn Thị Minh Khánh' : `Mẫu ${index + 1}`])) }),
  resolveValues: (context: any) => resolveDormitoryRosterPdfValues(context?.roster, context?.student),
};

export function createDefaultDormitoryLayout(pages: Array<{ pageIndex: number; width: number; height: number; rotation: number }>): PdfTemplateLayout {
  return { pages, items: fields.map(([fieldKey], index) => { const [left, top, width, height] = bounds[index]; return { id: `ktx-${createHash('sha1').update(fieldKey).digest('hex').slice(0, 10)}`, fieldKey, formatter: fieldKey.endsWith('dateOfBirth') || fieldKey.endsWith('IssueDate') ? 'date_ddmmyyyy' : fieldKey.endsWith('gender') ? 'gender_vi' : 'plain', pageIndex: 0, x: left / 595.32, y: top / 842.04, width: width / 595.32, height: height / 842.04, rotation: 0, zIndex: index, style: { ...style, overflow: 'shrink', maxLines: 1 } }; }) };
}

export function resolveDormitoryRosterPdfValues(roster: any, student: any) {
  const profile = roster?.applicant_profile || {}; const parent = (name: string) => profile[name] || {}; const linked = roster?.identity_state === 'LINKED' && student ? student : null;
  return { 'student.fullName': linked?.full_name || roster?.full_name || '', 'student.dateOfBirth': linked?.date_bir || roster?.date_of_birth || '', 'student.gender': linked?.sex || roster?.gender || '', 'student.className': linked?.class_id?.class_name || '', 'student.faculty': linked?.class_id?.dept_id?.name || '', 'applicant.ethnicity': profile.ethnicity || '', 'applicant.religion': profile.religion || '', 'roster.phone': roster?.phone_number || '', 'applicant.citizenId': profile.citizen_id_number || '', 'applicant.citizenIssueDate': profile.citizen_id_issue_date || '', 'applicant.citizenIssuePlace': profile.citizen_id_issue_place || '', 'applicant.permanentAddress': profile.permanent_address || '', 'parent.father.name': parent('father').full_name || '', 'parent.father.age': parent('father').age || '', 'parent.father.address': parent('father').permanent_address || '', 'parent.father.contactAddress': parent('father').contact_address || '', 'parent.father.occupation': parent('father').occupation || '', 'parent.father.phone': parent('father').phone_number || '', 'parent.mother.name': parent('mother').full_name || '', 'parent.mother.age': parent('mother').age || '', 'parent.mother.address': parent('mother').permanent_address || '', 'parent.mother.contactAddress': parent('mother').contact_address || '', 'parent.mother.occupation': parent('mother').occupation || '', 'parent.mother.phone': parent('mother').phone_number || '', 'applicant.priority': profile.priority_certificate_details || '' };
}
