'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { ExternalLink, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { Building, Room, dormitoryApi } from '@/api/dormitory-api';
import { useAuth } from '@/providers/auth-provider';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/Input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Research } from '@/components/ui/Research';
import ResponsiveDataView, { ResponsiveColumn } from '@/components/ui/ResponsiveDataView';
import { CustomPagination } from '@/components/ui/pagination';
import { toast } from 'sonner';

const roomDefaults = { ma_phong: '', ten_phong: '', building_id: '', tang: 1, loai_phong: 'Thường', so_giuong: 1, gia_phong: 0, trang_thai: 'Trống', mo_ta: '' };
const buildingDefaults = { ma_toa_nha: '', ten: '', dia_chi: '', so_tang: 1, trang_thai: 'Active', mo_ta: '' };

export default function BuildingsPage() {
  const { hasPermission } = useAuth();
  const canCreateRoom = hasPermission('DORM_ROOM_CREATE');
  const canUpdateRoom = hasPermission('DORM_ROOM_UPDATE');
  const canDeleteRoom = hasPermission('DORM_ROOM_DELETE');
  const canCreateBuilding = hasPermission('DORM_BUILDING_CREATE');
  const canUpdateBuilding = hasPermission('DORM_BUILDING_UPDATE');
  const canDeleteBuilding = hasPermission('DORM_BUILDING_DELETE');
  const [rooms, setRooms] = useState<Room[]>([]); const [buildings, setBuildings] = useState<Building[]>([]);
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const [meta, setMeta] = useState({ total: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const [roomOpen, setRoomOpen] = useState(false); const [buildingOpen, setBuildingOpen] = useState(false); const [roomEdit, setRoomEdit] = useState<Room | null>(null); const [buildingEdit, setBuildingEdit] = useState<Building | null>(null);
  const [roomForm, setRoomForm] = useState<any>(roomDefaults); const [buildingForm, setBuildingForm] = useState<any>(buildingDefaults); const [saving, setSaving] = useState(false);

  const load = useCallback(async (background = false) => {
    try { background ? setRefreshing(true) : setLoading(true); const [roomResult, buildingResult] = await Promise.all([dormitoryApi.rooms.getAll({ search: search.trim() || undefined, page, limit: pageSize }), dormitoryApi.buildings.getAll({ limit: 100 })]); setRooms(roomResult.data); setMeta(roomResult.meta); setBuildings(buildingResult.data); }
    catch (err: any) { toast.error(err?.message || 'Không thể tải danh sách phòng.'); } finally { setLoading(false); setRefreshing(false); }
  }, [search, page, pageSize]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [load]);
  const openRoom = (room?: Room) => { setRoomEdit(room || null); setRoomForm(room ? { ...room, building_id: typeof room.building_id === 'object' ? room.building_id._id : room.building_id, ten_phong: room.ten_phong || room.ma_phong } : { ...roomDefaults, building_id: buildings[0]?._id || '' }); setRoomOpen(true); };
  const openBuilding = (building?: Building) => { setBuildingEdit(building || null); setBuildingForm(building ? { ...building } : { ...buildingDefaults }); setBuildingOpen(true); };
  const saveRoom = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); try { const payload = { ...roomForm, so_giuong: Number(roomForm.so_giuong), tang: Number(roomForm.tang), gia_phong: Number(roomForm.gia_phong) }; if (roomEdit) await dormitoryApi.rooms.update(roomEdit._id, payload); else await dormitoryApi.rooms.create(payload); toast.success(roomEdit ? 'Đã cập nhật phòng' : 'Đã thêm phòng'); setRoomOpen(false); await load(true); } catch (err: any) { toast.error(err?.message || 'Không thể lưu phòng.'); } finally { setSaving(false); } };
  const saveBuilding = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); try { if (buildingEdit) await dormitoryApi.buildings.update(buildingEdit._id, buildingForm); else await dormitoryApi.buildings.create(buildingForm); toast.success(buildingEdit ? 'Đã cập nhật khu vực' : 'Đã thêm khu vực'); setBuildingOpen(false); await load(true); } catch (err: any) { toast.error(err?.message || 'Không thể lưu khu vực.'); } finally { setSaving(false); } };
  const removeRoom = async (room: Room) => { if (!confirm(`Xóa phòng ${room.ma_phong}?`)) return; try { await dormitoryApi.rooms.delete(room._id); toast.success('Đã xóa phòng'); await load(true); } catch (err: any) { toast.error(err?.message || 'Không thể xóa phòng.'); } };
  const removeBuilding = async (building: Building) => { if (!confirm(`Xóa khu vực ${building.ten}?`)) return; try { await dormitoryApi.buildings.delete(building._id); toast.success('Đã xóa khu vực'); await load(true); } catch (err: any) { toast.error(err?.message || 'Không thể xóa khu vực.'); } };
  const field = (label: string, key: string, type = 'text') => <div className="space-y-1.5"><label className="px-1 text-[13px] font-bold text-[#1E293B]">{label}</label><Input type={type} value={roomForm[key] ?? ''} onChange={e => setRoomForm((v: any) => ({ ...v, [key]: e.target.value }))} required={['ma_phong', 'ten_phong', 'building_id', 'so_giuong'].includes(key)} /></div>;
  const columns: ResponsiveColumn<Room>[] = [
    { key: 'ma_phong', header: 'Mã phòng', priority: 'primary' },
    { key: 'ten_phong', header: 'Tên phòng', priority: 'secondary', render: (v, r) => v || r.ma_phong },
    { key: 'so_giuong', header: 'Tổng số giường', render: v => String(v ?? 0) },
    { key: 'total_students', header: 'Tổng số sinh viên tại phòng', render: v => String(v ?? 0) },
    { key: 'actions', header: 'Thao tác', priority: 'action', render: (_, r) => <div className="flex items-center gap-1"><a aria-label="Mở trang QR phòng" title="Mở trang phòng" href={r.url_xem_nhanh || `/public/room/${r.ma_qr}`} target="_blank" rel="noreferrer" className="rounded-xl p-1.5 text-slate-500 hover:bg-blue-50"><ExternalLink size={15} /></a>{canUpdateRoom && <button aria-label="Sửa phòng" title="Sửa" onClick={() => openRoom(r)} className="rounded-xl p-1.5 text-blue-600 hover:bg-blue-50"><Pencil size={15} /></button>}{canDeleteRoom && <button aria-label="Xóa phòng" title="Xóa" onClick={() => void removeRoom(r)} className="rounded-xl p-1.5 text-red-600 hover:bg-red-50"><Trash2 size={15} /></button>}</div> },
  ];
  return <main className="flex h-full min-h-0 flex-col gap-3 overflow-y-auto bg-transparent p-4 custom-scrollbar sm:p-6">
    <div className="flex shrink-0 items-center gap-2 overflow-x-auto py-0.5"><Research aria-label="Tìm kiếm phòng" placeholder="Tìm mã hoặc tên phòng..." value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} containerClassName="hidden sm:flex w-[280px] shrink-0" /><button className="flex sm:hidden h-9 w-9 items-center justify-center rounded-xl border border-white/80 bg-white/50" aria-label="Tìm kiếm"><Search size={15} /></button><div className="ml-auto flex shrink-0 gap-2">{canCreateRoom && <Button variant="outline" aria-label="Thêm phòng" title="Thêm phòng" onClick={() => openRoom()} className="h-9 w-9 rounded-xl p-0"><Plus size={15} /></Button>}{canCreateBuilding && <Button variant="outline" aria-label="Thêm khu vực" title="Thêm khu vực" onClick={() => openBuilding()} className="h-9 w-9 rounded-xl p-0"><Plus size={15} /></Button>}<Button variant="outline" aria-label="Tải lại danh sách" title="Tải lại" onClick={() => void load(true)} className="h-9 w-9 rounded-xl p-0"><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} /></Button></div></div>
    <div className="flex min-h-0 flex-1 overflow-hidden rounded-2xl border border-white/70 bg-white/45 shadow-sm"><ResponsiveDataView data={rooms} columns={columns} isLoading={loading} keyExtractor={r => r._id} emptyState="Chưa có phòng nào" pagination={<CustomPagination totalItems={meta.total} pageSize={pageSize} currentPage={page} onPageChange={setPage} onPageSizeChange={s => { setPage(1); setPageSize(s); }} pageSizeOptions={[20, 40, 50, 100]} isLoading={loading} label="phòng" />} /></div>
    <div className="mt-2 flex flex-wrap gap-2">{buildings.map(b => <div key={b._id} className="rounded-xl border border-white/70 bg-white/45 px-3 py-2 text-xs text-slate-600">{b.ten}{canUpdateBuilding && <button aria-label={`Sửa khu vực ${b.ten}`} onClick={() => openBuilding(b)} className="ml-2 text-blue-600"><Pencil size={13} /></button>}{canDeleteBuilding && <button aria-label={`Xóa khu vực ${b.ten}`} onClick={() => void removeBuilding(b)} className="ml-1 text-red-600"><Trash2 size={13} /></button>}</div>)}</div>
    <Dialog open={roomOpen} onOpenChange={setRoomOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto rounded-2xl border border-white/80 bg-gradient-to-br from-[#EBF2FA] to-[#DCE6F1] p-6 shadow-2xl"><DialogHeader className="border-b border-white/50 pb-3"><DialogTitle>{roomEdit ? 'Sửa phòng' : 'Thêm phòng'}</DialogTitle></DialogHeader><form onSubmit={saveRoom} className="grid gap-4 py-4 sm:grid-cols-2">{field('Mã phòng', 'ma_phong')}{field('Tên phòng', 'ten_phong')}<div className="space-y-1.5"><label className="px-1 text-[13px] font-bold">Khu vực</label><Select value={roomForm.building_id} onValueChange={v => setRoomForm((x: any) => ({ ...x, building_id: v }))}><SelectTrigger><SelectValue placeholder="Chọn khu vực" /></SelectTrigger><SelectContent>{buildings.map(b => <SelectItem key={b._id} value={b._id}>{b.ten}</SelectItem>)}</SelectContent></Select></div>{field('Tầng', 'tang', 'number')}{field('Tổng số giường', 'so_giuong', 'number')}{field('Giá phòng', 'gia_phong', 'number')}<div className="space-y-1.5"><label className="px-1 text-[13px] font-bold">Trạng thái</label><Select value={roomForm.trang_thai} onValueChange={v => setRoomForm((x: any) => ({ ...x, trang_thai: v }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Trống">Trống</SelectItem><SelectItem value="Đầy">Đầy</SelectItem><SelectItem value="Khóa">Khóa</SelectItem><SelectItem value="Bảo trì">Bảo trì</SelectItem></SelectContent></Select></div><DialogFooter className="col-span-full border-t border-white/50 pt-4"><Button type="button" variant="outline" onClick={() => setRoomOpen(false)}>Hủy</Button><Button type="submit" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu phòng'}</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={buildingOpen} onOpenChange={setBuildingOpen}><DialogContent className="max-w-xl rounded-2xl border border-white/80 bg-gradient-to-br from-[#EBF2FA] to-[#DCE6F1] p-6 shadow-2xl"><DialogHeader className="border-b border-white/50 pb-3"><DialogTitle>{buildingEdit ? 'Sửa khu vực' : 'Thêm khu vực'}</DialogTitle></DialogHeader><form onSubmit={saveBuilding} className="space-y-4 py-4"><Input aria-label="Mã khu vực" placeholder="Mã khu vực" required value={buildingForm.ma_toa_nha} onChange={e => setBuildingForm((v: any) => ({ ...v, ma_toa_nha: e.target.value }))} /><Input aria-label="Tên khu vực" placeholder="Tên khu vực" required value={buildingForm.ten} onChange={e => setBuildingForm((v: any) => ({ ...v, ten: e.target.value }))} /><Input aria-label="Địa chỉ" placeholder="Địa chỉ" value={buildingForm.dia_chi} onChange={e => setBuildingForm((v: any) => ({ ...v, dia_chi: e.target.value }))} /><Input aria-label="Số tầng" type="number" min={1} value={buildingForm.so_tang} onChange={e => setBuildingForm((v: any) => ({ ...v, so_tang: Number(e.target.value) }))} /><DialogFooter className="border-t border-white/50 pt-4"><Button type="button" variant="outline" onClick={() => setBuildingOpen(false)}>Hủy</Button><Button type="submit" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu khu vực'}</Button></DialogFooter></form></DialogContent></Dialog>
  </main>;
}
